name: Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch: # allows you to trigger manually

jobs:
  build:
    name: python-${{ matrix.python }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        python: ['3.6', '3.7', '3.8']
    env:
      PYTHON: ${{ matrix.python }}
      OMPI_MCA_rmaps_base_oversubscribe: '1'
      OMPI_ALLOW_RUN_AS_ROOT: '1'
      OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: '1'
    steps:
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if ci/environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('ci/environment.yml') }}
      - name: Setup miniconda
        uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: pyconform # Defined in ci/environment.yml
          auto-update-conda: false
          python-version: ${{ matrix.python }}
          environment-file: ci/environment.yml
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      - name: Install package
        run: python -m pip install --no-deps .
      - name: Check Installation
        run: |
          conda list
          pip list
      - name: Run Tests
        run: ci/runtests.sh
      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          flags: unittests
          env_vars: PYTHON,MPI
          name: codecov-umbrella
          fail_ci_if_error: false
